# Generated by Django 3.2.8 on 2022-10-24 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('ozon', models.CharField(max_length=1000, null=True)),
                ('wb', models.CharField(max_length=1000, null=True)),
                ('ali', models.CharField(max_length=1000, null=True)),
                ('ym', models.CharField(max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.user')),
            ],
            options={
                'verbose_name': 'Link',
            },
        ),
    ]
