# Generated by Django 3.2.8 on 2022-11-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
