# Generated by Django 3.2.8 on 2022-12-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_link_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='btn_text',
            field=models.CharField(default='Перейти в приложение для покупок', max_length=100),
        ),
    ]
