# Generated by Django 3.2.8 on 2022-12-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_link_btn_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='btn_text',
        ),
        migrations.AddField(
            model_name='link',
            name='btn_text_ali',
            field=models.CharField(default='Перейти в приложение для покупок', max_length=100),
        ),
        migrations.AddField(
            model_name='link',
            name='btn_text_ozon',
            field=models.CharField(default='Перейти в приложение для покупок', max_length=100),
        ),
        migrations.AddField(
            model_name='link',
            name='btn_text_wb',
            field=models.CharField(default='Перейти в приложение для покупок', max_length=100),
        ),
        migrations.AddField(
            model_name='link',
            name='btn_text_ym',
            field=models.CharField(default='Перейти в приложение для покупок', max_length=100),
        ),
    ]
