# Generated by Django 4.1.2 on 2023-02-08 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_auto_20221205_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 1, 0, 0), verbose_name='Дата регистрации'),
        ),
        migrations.AddField(
            model_name='user',
            name='free',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
