# Generated by Django 4.1.6 on 2023-05-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_user_date_user_free_user_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Bonus',
            },
        ),
    ]
