# Generated by Django 4.1.6 on 2023-07-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_bonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Messages',
            },
        ),
    ]
