# Generated by Django 4.1.6 on 2023-10-14 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_messages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bonus',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='free',
        ),
        migrations.RemoveField(
            model_name='user',
            name='money',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
