# Generated by Django 4.1.6 on 2023-11-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_delete_bonus_remove_user_date_remove_user_free_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.TextField()),
                ('user', models.TextField()),
                ('in_out', models.BooleanField()),
            ],
            options={
                'verbose_name': 'History',
            },
        ),
        migrations.CreateModel(
            name='Invest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('user', models.TextField()),
                ('procent', models.TextField()),
                ('deadline', models.TextField()),
                ('maximum', models.TextField()),
            ],
            options={
                'verbose_name': 'Invest',
            },
        ),
        migrations.CreateModel(
            name='MoneyOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.TextField()),
                ('user', models.TextField()),
            ],
            options={
                'verbose_name': 'MoneyOut',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('procent', models.TextField()),
                ('deadline', models.TextField()),
                ('minimum', models.TextField()),
                ('maximum', models.TextField()),
                ('start_time', models.TextField()),
                ('end_time', models.TextField()),
            ],
            options={
                'verbose_name': 'Tariff',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='referal',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='time_zone',
            field=models.TextField(default=0),
        ),
    ]
