# Generated by Django 4.1.6 on 2023-11-07 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_history_invest_moneyout_tariff_user_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invest',
            old_name='maximum',
            new_name='sum',
        ),
    ]
