# Generated by Django 4.1.6 on 2023-11-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_rename_maximum_invest_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='invest',
            name='apply_out',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
