# Generated by Django 4.1.6 on 2023-11-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_invest_apply_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyout',
            name='card',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
