# Generated by Django 4.1.6 on 2023-11-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_moneyout_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyout',
            name='pay_id',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
