# Generated by Django 4.1.6 on 2023-11-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0015_moneyout_pay_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneyout',
            name='pay_id',
        ),
        migrations.AddField(
            model_name='history',
            name='pay_id',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
